default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: function_development

test:
  <<: *default
  database: function_test

production:
  <<: *default
  database: function_production
  username: function
  password: <%= ENV['FUNCTION_DATABASE_PASSWORD'] %>
